### ISSUE TITLE
FAQ command

### ISSUE THREAD

**Issue by goodideagiver** [NowYouKnowProgramming/jzp-docs#4]
W ile nauczę się programowania?

Jaka książka do języka x?

Czy do programowania potrzebny jest MacBook?

**Comment by Grewather** [comment]
Moje propozycje:
Czy do programowania potrzebny jest angielski/matematyka?
Czy warto iść na bootcamp?
Jakieś źródła do nauki programowania? (W odpowiedzi strona bewebdev.tech)

**Comment by s-jez** [comment]
Czy książki to dobry pomysł na naukę programowania?

Jaki język wybrać na start?

Co dalej po ukończeniu kursu z Udemy?

Jak tworzyć responsywne strony?

Czy mój kod jest poprawny semantycznie?

Gdzie mogę zacząć projektować stronę internetową?

Czy lepiej iść w Framework, czy lepiej poznać JavaScript?

Jak efektywnie mogę się uczyć programowania?? chcę widzieć swoje postępy

Czy kursy to dobry pomysł na naukę?

Jak szybko uzyskam swoją pierwszą pracę?

Czy wszyscy programiści zarabiają 15K?

**Comment by Piotrko64** [comment]
1. Czy muszę być dobry z Matematyki?

2. Na jakim stopniu powinienem umieć angielski?

3. Skąd mam wiedzieć czy stosuje dobre praktyki?

4. Czy Studia informatyczne są potrzebne jeśli chciałbym pracować jako Frontend?

5. Który framework JavaScriptowy jest teraz najbardziej opłacalny do nauki?

6. Czy FrontEndowiec powinien mieć opanowane zasady designu+ narzędzia typu figma? Jeśli tak to w jakim stopniu?

**Comment by goodideagiver** [comment]
Test

**Comment by goodideagiver** [comment]
## W ile nauczę się programowania?

Jeżeli nigdy nie miałeś styczności z programowaniem, musisz uzbroić się w cierpliwość, ponieważ na nauce podstaw programowania spędzisz prawdopodobnie 300-400 godzin. Ważne, abyś nie stracił na tym etapie motywacji i myślał o powodach, dla których postanowiłeś nauczyć się programować.

## Jaka książka do języka x?

Książki do języka programowania potrafią szybko stracić na aktualności, brakuje w nich też mi komentarzy od spolecznosci, gdzie można zweryfikować poprawność informacji. Polecamy korzystanie z internetu do nauki **języków**. 

## Czy do programowania potrzebny jest MacBook?

Nie, jeżeli nie programujesz w jezykach, które działają tylko na Apple. 

## Czy warto iść na bootcamp?

To zależy, duża ilość osób twierdzi, że lepiej nauczyć się wszystkiego samodzielnie i bootcamp jest zbyt drogi jak na to co oferuje. 

## Jakieś źródła do nauki programowania?

[bewebdev.tech](https://bewebdev.tech/)

## Jaki język wybrać na start?

Sprawdź oferty pracy, zrób własny przegląd co może ci się spodobać. 
Aktualnie najbardziej popularne są:

- JavaScript
- Python
- Java

## Co dalej po ukończeniu kursu z Udemy?

Rób projekty. 

Jak tworzyć responsywne strony?

[Tutaj wyjaśnienie](https://bewebdev.tech/technologies/css#responsive)

## Czy mój kod jest poprawny semantycznie?

[Sprawdź samemu](https://developer.mozilla.org/en-US/docs/Learn/HTML)

## Gdzie mogę zacząć projektować stronę internetową?

Figma, głowa, kartka, notatnik itp. 

## Czy lepiej iść w Framework, czy lepiej poznać JavaScript?

[Na przykładzie React: co trzeba umieć żeby zacząć](https://bewebdev.tech/technologies/react#what-to-know-before-react)

## Jak efektywnie mogę się uczyć programowania?

Ucz się regularnie i wykorzystuj wiedzę w praktyce. 

## Czy kursy to dobry pomysł na naukę?

Tak ale trzeba jednocześnie korzystać ze zdobytej wiedzy, samo oglądanie nie wystarczy. 

## Jak szybko uzyskam swoją pierwszą pracę?

Nie wiadomo, sytuacja jest bardzo ciężka i pewnie nigdy się nie poprawi. Trzeba mieć dużo szczęścia i umiejętności. 

## Czy muszę być dobry z Matematyki?

Zależy od tego jakie będziesz mieć zadania w pracy. Na frontend rzadziej potrzebne są takie umiejętności. Ale na rozmowach o pracę bardzo często musisz rozwiązywać algorytmy. 

## Na jakim stopniu powinienem umieć angielski?

W jak najlepszym, brak znajomości angielskiego skreśla cię u większości firm. 

## Skąd mam wiedzieć czy stosuje dobre praktyki?

[Sprawdzaj w internecie, weryfikuj](https://bewebdev.tech/principles/clean_code)

## Czy Studia informatyczne są potrzebne jeśli chciałbym pracować jako Frontend?

Nie

## Który framework JavaScriptowy jest teraz najbardziej opłacalny do nauki?

Sprawdź ogłoszenia o pracę

## Czy FrontEndowiec powinien mieć opanowane zasady designu+ narzędzia typu figma? Jeśli tak to w jakim stopniu?

Im więcej wiesz tym lepiej, dobrze jest mieć oko do detali. Jeżeli nie lubisz CSS, to być może frontend nie jest dla ciebie.
